---
title: "BaseballSavant"
format: html
---

```{r}
library(tidyverse)
library(mgcv)
library(purrr)
library(jsonlite)
```

Load in Data
```{r}
KCLyakkertechData <- read_csv("KCLYakkertechData.csv")
BeltersyakkertechData <- read_csv("BeltersYakkertechData.csv")
```


Function to calculate advanced hitting stats
```{r}
getAdvancedHitting <- function(df, name){
  df <- df |> 
    filter(Batter == name)
  
  avgExitVelo <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(avgExitVelo = mean(ExitSpeed)) |> 
    pull(avgExitVelo)
  
  maxExitVelo <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(max = if (n()==0) NA_real_ else max(ExitSpeed)) |> 
    pull(max)
  
  LASweetSpot <- df |> 
    filter(!is.na(Angle)) |> 
    summarize(pct = mean(Angle >= 8 & Angle <= 32)) |> 
    pull(pct)
  
  hardHitPct <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(pct = mean(ExitSpeed >= 90)) |> 
    pull(pct)
  
  squaredUpPct <- df |> 
    filter(!is.na(Angle) & !is.na(ExitSpeed)) |> 
    summarize(pct = mean(Angle >= 8 & Angle <= 32 & ExitSpeed >= 90)) |> 
    pull(pct)
  
  kPct <- df |> 
    filter(!is.na(PlayResult) | !is.na(KorBB) | PitchCall == "HitByPitch") |> 
    summarize(
      pct = {
        total_PA <- n()
        strikeouts <- sum(
          PlayResult %in% c("StrikeoutLooking", "StrikeoutSwinging"), na.rm = TRUE
        )
      if(total_PA == 0) 0 else strikeouts / total_PA
      }
    ) |> 
    pull(pct)
  
  bbPct <- df |> 
    filter(!is.na(PlayResult) | !is.na(KorBB)) |>
    summarize(pct = sum(KorBB == "Walk", na.rm = TRUE) / n()) |> 
    pull(pct)
  
  whiffPct <- df |> 
    filter(!is.na(PitchCall)) |> 
    filter(!(PitchCall %in% c("BallCalled", "HitByPitch", "StrikeCalled"))) |> 
    summarize(pct = mean(PitchCall == "StrikeSwinging")) |> 
    pull(pct)
  
  chasePct <- df |> 
    filter(IsStrike == FALSE) |> 
    summarize(pct = mean(IsSwing == TRUE)) |> 
    pull(pct)
  
  xBA <- df |> 
    filter(!is.na(PlayResult)) |> 
    summarize(avg = mean(predicted_xba)) |> 
    pull(avg)
  
  xSLG <- df |> 
    filter(!is.na(PlayResult)) |> 
    summarize(avg = mean(predicted_xslg)) |> 
    pull(avg)
  
  xWOBA <- df |> 
    filter(!is.na(PlayResult)) |> 
    summarize(avg = mean(predicted_xwoba)) |> 
    pull(avg)
  
  xBABIP <- df |> 
    filter(predicted_xba > 0) |> 
    summarize(avg = mean(predicted_xba)) |> 
    pull(avg)
  
  babip <- df |> 
    filter(PitchCall == "InPlay" & !is.na(PlayResult)) |> 
    summarize(avg = sum(PlayResult %in% c("Single","Double","Triple","HomeRun")) / n()) |> 
    pull(avg)
  
  return(
    list(
      avgExitVelo = avgExitVelo,
      maxExitVelo = maxExitVelo,
      LASweetSpot = LASweetSpot,
      hardHitPct = hardHitPct,
      squaredUpPct = squaredUpPct,
      kPct = kPct,
      bbPct = bbPct,
      whiffPct = whiffPct,
      chasePct = chasePct,
      xBA = xBA,
      xSLG = xSLG,
      xWOBA = xWOBA,
      xBABIP = xBABIP,
      babip = babip
    )
  )
    
}

```

Function to calculate advanced pitching stats
```{r}
getAdvancedPitching <- function(df, name) {
  df <- df |> 
    filter(Pitcher == name)
  
  FastballVelo <- df |> 
    filter(TaggedPitchType == "Fastball") |> 
    summarize(velo = mean(RelSpeed)) |> 
    pull(velo)
  
  avgExitVelo <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(
      avgExitVelo = mean(ExitSpeed)
    ) |> 
  pull(avgExitVelo)
  
  hardHitPct <- df |> 
    filter(!is.na(ExitSpeed)) |> 
    summarize(pct = mean(ExitSpeed >= 95)) |> 
    pull(pct)
  
  kPct <- df |> 
    filter(!is.na(PlayResult) | !is.na(KorBB)) |> 
    summarize(
      pct = {
        total_PA <- n()
        strikeouts <- sum(
          PlayResult %in% c("StrikeoutLooking", "StrikeoutSwinging"), na.rm = TRUE
        )
      if(total_PA == 0) 0 else strikeouts / total_PA
      }
    ) |> 
    pull(pct)
  
  bbPct <- df |> 
    filter(!is.na(PlayResult) | !is.na(KorBB)) |>
    summarize(pct = sum(KorBB == "Walk", na.rm = TRUE) / n()) |> 
    pull(pct)
  
  whiffPct <- df |> 
    filter(!is.na(PitchCall)) |> 
    filter(!(PitchCall %in% c("BallCalled", "HitByPitch", "StrikeCalled"))) |> 
    summarize(pct = mean(PitchCall == "StrikeSwinging")) |> 
    pull(pct)
  
  chasePct <- df |> 
    filter(IsStrike == FALSE) |> 
    summarize(pct = mean(IsSwing == TRUE)) |> 
    pull(pct)
  
  groundBallPct <- df |> 
    filter(!is.na(HitType) & HitType != "Throwdown") |> 
    summarize(pct = mean(HitType == "GroundBall")) |> 
    pull(pct)
  
  
}
```


Creating Batter Advanced Stats Dataframe
```{r}
kcl_batter_list <- split(KCLyakkertechData, KCLyakkertechData$Batter)

kcl_advanced_by_batter <- map2_df(
  .x = kcl_batter_list,
  .y = names(kcl_batter_list),
  ~ as_tibble(getAdvancedHitting(.x, .y)),
  .id = "Batter"
)

belters_batter_list <- split(BeltersyakkertechData, BeltersyakkertechData$Batter)

belters_advanced_by_batter <- map2_df(
  .x = belters_batter_list,
  .y = names(belters_batter_list),
  ~ as_tibble(getAdvancedHitting(.x, .y)),
  .id = "Batter"
)

invert_cols <- c("kPct", "whiffPct", "chasePct")

kcl_advanced_by_batter <- kcl_advanced_by_batter |> 
  mutate(
    across(
      .cols = where(is.numeric) & !all_of(invert_cols),
      .fns  = ~ percent_rank(.) * 100,
      .names = "{.col}_pct"
    )
  ) |> 
  mutate(
    across(
      .cols = all_of(invert_cols),
      .fns  = ~ percent_rank(-.) * 100,
      .names = "{.col}_pct"
    )
  )

belters_advanced_by_batter <- belters_advanced_by_batter |> 
  mutate(
    across(
      .cols = where(is.numeric) & !all_of(invert_cols),
      .fns  = ~ percent_rank(.) * 100,
      .names = "{.col}_pct"
    )
  ) |> 
  mutate(
    across(
      .cols = all_of(invert_cols),
      .fns  = ~ percent_rank(-.) * 100,
      .names = "{.col}_pct"
    )
  )

```

Attach basic hitting stats to advanced stats (ONLY FOR KCL)
```{r}
kcl_basicStats_files <- c(
  "KCLStats/bluecapsStatsFinal.csv",
  "KCLStats/bobcatsStatsFinal.csv",
  "KCLStats/groundslothsStatsFinal.csv",
  "KCLStats/merchantsStatsFinal.csv"
)

kcl_basic_stats_dfs <- kcl_basicStats_files |> 
  map(read_csv)

KCLBasicStats <- bind_rows(kcl_basic_stats_dfs) |> 
  filter(Name != "Total") |> 
  rename(Batter = Name)
#write_csv(KCLBasicStats, "KCLBasicStats.csv")

KCLSavantData <- kcl_advanced_by_batter |> 
  left_join(KCLBasicStats, by = "Batter") |> 
  select(-GP, -R, -`2B`, -`3B`, -RBI, -TB, -BB, -SO)

beltersBasicStats <- read_csv("beltersStats.csv")
belters_advanced_by_batter <- belters_advanced_by_batter |> 
  left_join(beltersBasicStats, by = "Batter") |> 
  select(-Number, -Year, -Position, -GP, -RBI, -BB, -K, -HBP, -SF, -SH, -HDP, -GO, -FO, -"GO/FO", -PA, -`2B`, -`3B`, -XBH) |> 
  mutate(
    HR = parse_double(HR),
    SB = replace_na(SB, 0)
  )

```

Put in new xWOBA con
```{r}
xWOBA_2 <- read_csv("YakkertechData/xWOBA_KCL/Hitter_XWOBA.csv") |> 
  select(Batter, xWOBA, Percentile) |> 
  rename(xWOBA_2 = xWOBA,
         xWOBA_2_pct = Percentile)

KCLSavantData <- KCLSavantData |> 
  left_join(xWOBA_2, by = "Batter")

xWOBA_2 <- read_csv("YakkertechData/xWOBA_CornBelters/xWOBA_Data_Belters.csv") |> 
  select(Batter, xWOBA, Percentile) |> 
  rename(xWOBA_2 = xWOBA,
         xWOBA_2_pct = Percentile)

BeltersSavantData <- belters_advanced_by_batter |> 
  left_join(xWOBA_2, by = "Batter")

```

Save Savant Data
```{r}
savantData <- bind_rows(KCLSavantData, BeltersSavantData)
write_csv(KCLSavantData, "KCLSavantData.csv")
write_csv(BeltersSavantData, "BeltersSavantData.csv")
write_csv(savantData, "SavantData.csv")
```








